/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.1.1/samples
 */

plugins {
	java
	application
	id("org.jetbrains.kotlin.jvm") version "1.8.21"
}

repositories {
	mavenCentral() 
}

java {                                      
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

application {
	mainClass.set("pt.isel.leic.lae.ChequenceAppKt")
}
